deployment:
  tasks:
    - export DEPLOY_PATH=/home/wetntcom/repositories/tests
    - /usr/bin/git -C $DEPLOY_PATH reset --hard
    - /usr/bin/git -C $DEPLOY_PATH pull origin main
    - echo "Despliegue completado en $(date)" >> $DEPLOY_PATH/deploy.log
